### ISSUE TITLE
Time.pluralize()

### ISSUE THREAD

**Issue by tsmith3390** [abhidsm/time_diff#1]
You Have:

return count > 1 ? word.pluralize : word

Should Be:

return count != 1 ? word.pluralize : word

As Years, Months, Weeks, Etc With A Value Of 0 Are Still Pluralized, Only Those With A Value Of 1 Aren't.
For Example: 0 Years, 1 Month, 0 Weeks, 1 Day, 0 Hours, 1 Minute, 0 Seconds.

Built Own Gem And Worked Correctly.

**Comment by abhidsm** [comment]
Thanks Smith.

I've updated the gem with the fix you provided.
