### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by sethiele** [abhidsm/time_diff#4]
As I can see in your Code, the gem don't support i18n? If so, could you add this support? And If it is supported could you document it please?

Thank you for your work.

**Comment by abhidsm** [comment]
Can you please explain why you need the support for i18n?

**Comment by sethiele** [comment]
Hi,
for example to translate the diff week/ weeks & day/ days.

**Comment by kingM** [comment]
hi,

I have the same problem, how do I translate days, months, weeks, hours, minutes ...
